const data=window.MQ_DATA,canvas=document.getElementById('screen'),ctx=canvas.getContext('2d');
const images={},descriptions={talk:'Chuỗi lặp: môi đóng/mở, thay đổi biểu cảm khi nói chuyện.',laser:'Chuẩn bị → gom năng lượng → gồng → bắn laser từ lòng bàn tay → tắt tia → hồi tư thế.',hit:'Trúng đòn → giật lùi → chao người → lấy lại thăng bằng → phòng thủ.',taunt:'Ngẩng cằm → cười khẩy → xua tay khinh thường → trở về tư thế.',defeat:'Chao đảo → khuỵu gối → chống tay → tắt năng lượng. Giữ nguyên khung cuối.',missile_single:'Mở ống phóng ở vai → ngắm → bắn một tên lửa → tên lửa bay và nổ → đóng giáp.',missile_rain:'Mở hai cụm phóng → bắn loạt 6 tên lửa lên cao → tên lửa rơi xuống theo mưa → đóng giáp.'};
let current='talk',frame=0,playing=true,elapsed=0,last=0,ready=false;
const $=id=>document.getElementById(id);
function select(id){current=id;frame=0;elapsed=0;playing=true;$('loop').checked=data.clips[id].loop;update();for(const b of $('clips').children)b.setAttribute('aria-pressed',String(b.dataset.id===id));}
for(const [id,clip]of Object.entries(data.clips)){const button=document.createElement('button');button.dataset.id=id;button.innerHTML=clip.label+'<small>6 khung · '+(clip.loop?'lặp':'phát một lần')+'</small>';button.setAttribute('aria-pressed',String(id===current));button.onclick=()=>select(id);$('clips').append(button)}
function update(){$('caption').textContent=data.clips[current].label;$('description').textContent=descriptions[current];$('sheet').href=data.clips[current].frames[frame].file;$('scrub').value=frame;$('counter').textContent=(frame+1)+' / 6';$('play').textContent=playing?'Tạm dừng':'Tiếp tục';}
function draw(){ctx.clearRect(0,0,960,620);if(!ready)return;const clip=data.clips[current],f=clip.frames[frame];const scale=440/clip.referenceHeight;const anchorX=current==='laser'?320:current==='missile_single'?650:current==='missile_rain'?285:480,ground=550;
 ctx.save();if(!$('checker').checked){const grad=ctx.createRadialGradient(anchorX,ground,5,anchorX,ground,200);grad.addColorStop(0,'#42c9ff30');grad.addColorStop(1,'#42c9ff00');ctx.fillStyle=grad;ctx.beginPath();ctx.ellipse(anchorX,ground+8,200,25,0,0,Math.PI*2);ctx.fill();}
 ctx.drawImage(images[current][frame],anchorX-f.pivot.x*scale,ground-f.pivot.y*scale,f.w*scale,f.h*scale);ctx.restore();if(current.startsWith('missile_')){const time=clip.frames.slice(0,frame).reduce((sum,f)=>sum+f.durationMs,0)+elapsed;MQ_MISSILES.draw(ctx,current,time,anchorX,ground,images.projectile,data.projectile);}}
function tick(time){const delta=last?Math.min(time-last,100):0;last=time;if(playing&&ready){elapsed+=delta*Number($('speed').value);let duration=data.clips[current].frames[frame].durationMs;while(elapsed>=duration&&playing){elapsed-=duration;if(frame<5)frame++;else if($('loop').checked)frame=0;else{playing=false;elapsed=0}duration=data.clips[current].frames[frame].durationMs;update()}}draw();requestAnimationFrame(tick)}
$('play').onclick=()=>{if(!playing&&frame===5&&!$('loop').checked){frame=0;elapsed=0}playing=!playing;update()};$('restart').onclick=()=>{frame=0;elapsed=0;playing=true;update()};$('scrub').oninput=()=>{frame=Number($('scrub').value);elapsed=0;playing=false;update();draw()};$('checker').onchange=()=>{$('stage').classList.toggle('checker',$('checker').checked);draw()};
const loads=Object.entries(data.clips).flatMap(([id,clip])=>clip.frames.map((f,index)=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{images[id]??=[];images[id][index]=image;resolve()};image.onerror=()=>reject(Error('Không tải được '+f.file));image.src=f.file})));
loads.push(new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{images.projectile=image;resolve()};image.onerror=()=>reject(Error('Không tải được tên lửa'));image.src=data.projectile.file}));
Promise.all(loads).then(()=>{ready=true;const requested=new URLSearchParams(location.search).get('clip');select(data.clips[requested]?requested:'talk');requestAnimationFrame(tick)}).catch(e=>{$('caption').textContent=e.message;console.error(e)});
window.MQ_PLAYER={select,seekTime(ms){const clip=data.clips[current];frame=0;elapsed=Math.max(0,ms);while(frame<5&&elapsed>=clip.frames[frame].durationMs){elapsed-=clip.frames[frame].durationMs;frame++}elapsed=Math.min(elapsed,clip.frames[frame].durationMs);playing=false;update();draw()},get state(){return{current,frame,playing,ready}},draw};
