const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/WBPC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=__dirname;
function crc32(b){let c=0xffffffff;for(const v of b){c^=v;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(type,data){let t=Buffer.from(type),n=Buffer.alloc(4),crc=Buffer.alloc(4);n.writeUInt32BE(data.length);crc.writeUInt32BE(crc32(Buffer.concat([t,data])));return Buffer.concat([n,t,data,crc]);}
function parsePNG(buf){let out=[];for(let p=8;p<buf.length;){let n=buf.readUInt32BE(p),type=buf.toString('ascii',p+4,p+8);out.push({type,data:buf.subarray(p+8,p+8+n)});p+=n+12;}return out;}
function apng(frames){let parsed=frames.map(parsePNG),header=parsed[0].find(c=>c.type==='IHDR').data;let ac=Buffer.alloc(8);ac.writeUInt32BE(frames.length);let out=[frames[0].subarray(0,8),chunk('IHDR',header),chunk('acTL',ac)],seq=0;parsed.forEach((cs,i)=>{let fc=Buffer.alloc(26);fc.writeUInt32BE(seq++,0);fc.writeUInt32BE(header.readUInt32BE(0),4);fc.writeUInt32BE(header.readUInt32BE(4),8);fc.writeUInt16BE(100,20);fc.writeUInt16BE(1000,22);out.push(chunk('fcTL',fc));for(const c of cs.filter(c=>c.type==='IDAT')){if(i===0)out.push(chunk('IDAT',c.data));else{let n=Buffer.alloc(4);n.writeUInt32BE(seq++);out.push(chunk('fdAT',Buffer.concat([n,c.data])));}}});out.push(chunk('IEND',Buffer.alloc(0)));return Buffer.concat(out);}
const server=http.createServer((req,res)=>{try{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}res.setHeader('Content-Type',p.endsWith('.html')?'text/html; charset=utf-8':p.endsWith('.png')?'image/png':'application/octet-stream');res.end(fs.readFileSync(p));}catch(e){res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1180,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/xem_thu_chien_dau.html`);await page.waitForFunction(()=>window.combatPreview?.getState().ready,{timeout:60000});console.log(JSON.stringify(await page.evaluate(()=>combatPreview.getState())));
for(const pose of await page.evaluate(()=>combatPreview.data.poses))await page.evaluate(p=>combatPreview.selectPose(p),pose);
for(const action of ['idle','think','fire','ice','sky','lightning','small','hit','win']){for(const t of [0,360,720,1100,2000,6000])await page.evaluate(({action,t})=>combatPreview.seek(action,t),{action,t});}
await page.evaluate(()=>combatPreview.seek('hit',6000));if((await page.evaluate(()=>combatPreview.getState().frame.pose))!=='guc')throw Error('Defeat does not hold');
await page.locator('#play').click();let t1=await page.evaluate(()=>combatPreview.getState().time);await page.waitForTimeout(180);if((await page.evaluate(()=>combatPreview.getState().time))<=t1)throw Error('Playback stopped');await page.locator('#play').click();
for(const sex of ['nam','nu']){let url=await page.evaluate(s=>combatPreview.exportBoard(s),sex);fs.writeFileSync(path.join(root,sex,'reference',`reference_chien_dau_${sex}.png`),Buffer.from(url.split(',')[1],'base64'));await page.evaluate(()=>combatPreview.seek('fire',1320));url=await page.evaluate(s=>combatPreview.exportScene(s),sex);fs.writeFileSync(path.join(root,sex,'reference',`reference_canh_chien_dau_${sex}_cho_boss.png`),Buffer.from(url.split(',')[1],'base64'));}
for(const sex of ['nam','nu'])for(const [action,name] of (process.argv.includes('--meteor-only')?[['sky','thien_thach_va_cham']]:[['lightning','set_dien_giat'],['sky','thien_thach_va_cham']])){const frames=[];for(let i=0;i<27;i++){await page.evaluate(({action,time})=>combatPreview.seek(action,time),{action,time:i*100});let url=await page.evaluate(s=>{let c=document.createElement('canvas');c.width=836;c.height=471;c.getContext('2d').drawImage(document.getElementById(s),0,0,836,471);return c.toDataURL('image/png');},sex);frames.push(Buffer.from(url.split(',')[1],'base64'));}fs.writeFileSync(path.join(root,`${sex}_${name}_2d.png`),apng(frames));}
for(const [action,time] of [['lightning',1110],['sky',1660]]){await page.evaluate(({action,time})=>combatPreview.seek(action,time),{action,time});let url=await page.evaluate(()=>combatPreview.exportScene('nam'));fs.writeFileSync(path.join(root,`kiem_tra_${action}_va_cham.png`),Buffer.from(url.split(',')[1],'base64'));}
await page.screenshot({path:path.join(root,'kiem_tra_ban_xem_thu.png'),fullPage:true});if(errors.length)throw Error(errors.join('\n'));console.log('PASS all30poses,9actions,play/pause,defeat-hold; exported4references and4impact APNG animations; no pageerrors');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
