// Danh mục đồ vật cho tranh "Tìm Nhân Vật Ẩn" + "Tìm Điểm Khác Nhau" (Thùy 25/09: không tự vẽ, dùng asset đẹp).
// Nguồn hình: Microsoft Fluent Emoji 3D (MIT) — github.com/microsoft/fluentui-emoji, thư mục assets/<Tên>/3D/.
// Mỗi WORLD = 1 chủ đề: bộ đồ vật riêng + kiểu nền riêng. [tên thư mục Fluent, tên tiếng Việt hiện cho học sinh, vùng]
// vùng: 'sky' (trên trời) · 'ground' (mặt đất/sàn) · 'water' (dưới nước) · 'any'
export const WORLDS = {
  trungthu: { vn: 'Đêm hội Trung Thu', bg: 'night-hills', items: [
    ['Red paper lantern', 'Đèn lồng đỏ', 'sky'], ['Full moon', 'Trăng tròn', 'sky'], ['Moon cake', 'Bánh trung thu', 'ground'],
    ['Dragon', 'Con rồng', 'ground'], ['Carp streamer', 'Cờ cá chép', 'sky'], ['Diya lamp', 'Đèn dầu', 'ground'],
    ['Rabbit', 'Chú thỏ', 'ground'], ['Star', 'Ngôi sao', 'sky'], ['Glowing star', 'Sao lấp lánh', 'sky'], ['Kite', 'Con diều', 'sky'],
    ['Drum', 'Cái trống', 'ground'], ['Lion', 'Sư tử', 'ground'], ['Teacup without handle', 'Chén trà', 'ground'], ['Teapot', 'Ấm trà', 'ground'],
    ['Tangerine', 'Quả quýt', 'ground'], ['Grapes', 'Chùm nho', 'ground'], ['Balloon', 'Bóng bay', 'sky'], ['Candle', 'Cây nến', 'ground'],
    ['Crescent moon', 'Trăng khuyết', 'sky'], ['Dango', 'Xiên bánh', 'ground'], ['Chestnut', 'Hạt dẻ', 'ground'], ['Firecracker', 'Pháo', 'ground'],
    ['Wind chime', 'Chuông gió', 'sky'], ['Magic wand', 'Đũa phép', 'ground'], ['Crown', 'Vương miện', 'ground'], ['Teddy bear', 'Gấu bông', 'ground'] ] },
  farm: { vn: 'Nông trại', bg: 'day-farm', items: [
    ['Cow', 'Con bò', 'ground'], ['Pig', 'Con lợn', 'ground'], ['Chicken', 'Con gà', 'ground'], ['Rooster', 'Gà trống', 'ground'],
    ['Hatching chick', 'Gà con', 'ground'], ['Horse', 'Con ngựa', 'ground'], ['Ewe', 'Con cừu', 'ground'], ['Goat', 'Con dê', 'ground'],
    ['Duck', 'Con vịt', 'ground'], ['Tractor', 'Máy cày', 'ground'], ['Ear of corn', 'Bắp ngô', 'ground'], ['Carrot', 'Củ cà rốt', 'ground'],
    ['Sunflower', 'Hoa hướng dương', 'ground'], ['Jack-o-lantern', 'Quả bí', 'ground'], ['Egg', 'Quả trứng', 'ground'], ['Basket', 'Cái giỏ', 'ground'],
    ['Sheaf of rice', 'Bó lúa', 'ground'], ['Hut', 'Túp lều', 'ground'], ['Dog', 'Con chó', 'ground'], ['Cat', 'Con mèo', 'ground'],
    ['Rabbit', 'Chú thỏ', 'ground'], ['Honeybee', 'Con ong', 'sky'], ['Sun', 'Mặt trời', 'sky'], ['Cloud', 'Đám mây', 'sky'],
    ['Bird', 'Chú chim', 'sky'], ['Potato', 'Củ khoai tây', 'ground'], ['Eggplant', 'Quả cà tím', 'ground'], ['Watermelon', 'Quả dưa hấu', 'ground'] ] },
  forest: { vn: 'Rừng xanh', bg: 'day-forest', items: [
    ['Deer', 'Con nai', 'ground'], ['Fox', 'Con cáo', 'ground'], ['Bear', 'Con gấu', 'ground'], ['Chipmunk', 'Con sóc', 'ground'],
    ['Owl', 'Con cú', 'sky'], ['Hedgehog', 'Con nhím', 'ground'], ['Mushroom', 'Cây nấm', 'ground'], ['Evergreen tree', 'Cây thông', 'ground'],
    ['Deciduous tree', 'Cây xanh', 'ground'], ['Maple leaf', 'Lá phong', 'sky'], ['Snail', 'Con ốc sên', 'ground'], ['Butterfly', 'Con bướm', 'sky'],
    ['Lady beetle', 'Bọ rùa', 'ground'], ['Honeybee', 'Con ong', 'sky'], ['Wolf', 'Con sói', 'ground'], ['Raccoon', 'Gấu mèo', 'ground'],
    ['Badger', 'Con lửng', 'ground'], ['Frog', 'Con ếch', 'ground'], ['Turtle', 'Con rùa', 'ground'], ['Beaver', 'Hải ly', 'ground'],
    ['Feather', 'Chiếc lông', 'sky'], ['Fallen leaf', 'Lá rụng', 'sky'], ['Herb', 'Cây lá', 'ground'], ['Tent', 'Cái lều', 'ground'],
    ['Wood', 'Khúc gỗ', 'ground'], ['Rock', 'Hòn đá', 'ground'], ['Eagle', 'Đại bàng', 'sky'], ['Bat', 'Con dơi', 'sky'] ] },
  beach: { vn: 'Bãi biển', bg: 'day-beach', items: [
    ['Crab', 'Con cua', 'ground'], ['Tropical fish', 'Cá nhiệt đới', 'water'], ['Fish', 'Con cá', 'water'], ['Dolphin', 'Cá heo', 'water'],
    ['Octopus', 'Bạch tuộc', 'water'], ['Spiral shell', 'Vỏ ốc', 'ground'], ['Sailboat', 'Thuyền buồm', 'water'], ['Umbrella on ground', 'Ô che nắng', 'ground'],
    ['Palm tree', 'Cây dừa', 'ground'], ['Spouting whale', 'Cá voi', 'water'], ['Shrimp', 'Con tôm', 'water'], ['Lobster', 'Tôm hùm', 'water'],
    ['Coral', 'San hô', 'water'], ['Blowfish', 'Cá nóc', 'water'], ['Shark', 'Cá mập', 'water'], ['Seal', 'Hải cẩu', 'ground'],
    ['Coconut', 'Quả dừa', 'ground'], ['Sun', 'Mặt trời', 'sky'], ['Cloud', 'Đám mây', 'sky'], ['Kite', 'Con diều', 'sky'],
    ['Canoe', 'Ca nô', 'water'], ['Speedboat', 'Xuồng máy', 'water'], ['Tropical drink', 'Nước dừa', 'ground'], ['Sunglasses', 'Kính râm', 'ground'],
    ['Thong sandal', 'Dép tông', 'ground'], ['Volleyball', 'Bóng chuyền', 'ground'], ['Jellyfish', 'Sứa biển', 'water'], ['Water wave', 'Con sóng', 'water'] ] },
  fruit: { vn: 'Chợ trái cây', bg: 'day-market', items: [
    ['Red apple', 'Quả táo đỏ', 'any'], ['Green apple', 'Quả táo xanh', 'any'], ['Banana', 'Quả chuối', 'any'], ['Grapes', 'Chùm nho', 'any'],
    ['Watermelon', 'Quả dưa hấu', 'any'], ['Strawberry', 'Quả dâu tây', 'any'], ['Pineapple', 'Quả dứa', 'any'], ['Mango', 'Quả xoài', 'any'],
    ['Peach', 'Quả đào', 'any'], ['Cherries', 'Quả anh đào', 'any'], ['Lemon', 'Quả chanh', 'any'], ['Tangerine', 'Quả quýt', 'any'],
    ['Pear', 'Quả lê', 'any'], ['Kiwi fruit', 'Quả kiwi', 'any'], ['Coconut', 'Quả dừa', 'any'], ['Avocado', 'Quả bơ', 'any'],
    ['Melon', 'Quả dưa lưới', 'any'], ['Blueberries', 'Việt quất', 'any'], ['Tomato', 'Quả cà chua', 'any'], ['Hot pepper', 'Quả ớt', 'any'],
    ['Bell pepper', 'Ớt chuông', 'any'], ['Cucumber', 'Quả dưa chuột', 'any'], ['Broccoli', 'Bông cải xanh', 'any'], ['Garlic', 'Củ tỏi', 'any'],
    ['Onion', 'Củ hành', 'any'], ['Peanuts', 'Hạt lạc', 'any'], ['Olive', 'Quả ô liu', 'any'], ['Leafy green', 'Rau xanh', 'any'] ] },
  party: { vn: 'Tiệc sinh nhật', bg: 'room-party', items: [
    ['Birthday cake', 'Bánh sinh nhật', 'ground'], ['Balloon', 'Bóng bay', 'sky'], ['Party popper', 'Pháo giấy', 'any'], ['Wrapped gift', 'Hộp quà', 'ground'],
    ['Confetti ball', 'Quả cầu giấy', 'sky'], ['Candy', 'Viên kẹo', 'any'], ['Lollipop', 'Kẹo mút', 'any'], ['Cupcake', 'Bánh cupcake', 'ground'],
    ['Soft ice cream', 'Kem ốc quế', 'any'], ['Doughnut', 'Bánh donut', 'any'], ['Cookie', 'Bánh quy', 'any'], ['Teddy bear', 'Gấu bông', 'ground'],
    ['Partying face', 'Mặt vui tiệc', 'any'], ['Ribbon', 'Nơ ruy băng', 'sky'], ['Tanabata tree', 'Cây ước nguyện', 'ground'], ['Piñata', 'Pinata', 'sky'],
    ['Chocolate bar', 'Thanh sô-cô-la', 'any'], ['Custard', 'Bánh flan', 'any'], ['Shortcake', 'Bánh kem dâu', 'any'], ['Bubble tea', 'Trà sữa', 'any'],
    ['Cup with straw', 'Ly nước', 'any'], ['Pizza', 'Bánh pizza', 'any'], ['Popcorn', 'Bắp rang', 'any'], ['Musical note', 'Nốt nhạc', 'sky'],
    ['Microphone', 'Micro', 'any'], ['Guitar', 'Đàn guitar', 'ground'], ['Crown', 'Vương miện', 'any'], ['Magic wand', 'Đũa phép', 'any'] ] },
  toys: { vn: 'Phòng đồ chơi', bg: 'room-toys', items: [
    ['Teddy bear', 'Gấu bông', 'ground'], ['Kite', 'Con diều', 'sky'], ['Yo-yo', 'Con quay yo-yo', 'any'], ['Puzzle piece', 'Mảnh ghép', 'any'],
    ['Soccer ball', 'Quả bóng đá', 'ground'], ['Basketball', 'Quả bóng rổ', 'ground'], ['Game die', 'Xúc xắc', 'any'], ['Robot', 'Người máy', 'ground'],
    ['Rocket', 'Tên lửa', 'sky'], ['Automobile', 'Ô tô', 'ground'], ['Kick scooter', 'Xe trượt', 'ground'], ['Skateboard', 'Ván trượt', 'ground'],
    ['Video game', 'Tay cầm game', 'any'], ['Joystick', 'Cần điều khiển', 'any'], ['Nesting dolls', 'Búp bê Nga', 'ground'], ['Artist palette', 'Bảng màu', 'any'],
    ['Crayon', 'Bút sáp', 'any'], ['Books', 'Chồng sách', 'ground'], ['Teddy bear', 'Gấu bông', 'ground'], ['Balloon', 'Bóng bay', 'sky'],
    ['Drum', 'Cái trống', 'ground'], ['Trumpet', 'Kèn trumpet', 'any'], ['Violin', 'Đàn violin', 'any'], ['Bowling', 'Bowling', 'ground'],
    ['Magic wand', 'Đũa phép', 'any'], ['Crystal ball', 'Quả cầu pha lê', 'any'], ['Pool 8 ball', 'Bi số 8', 'any'], ['Flying disc', 'Đĩa ném', 'sky'] ] },
  garden: { vn: 'Vườn hoa', bg: 'day-garden', items: [
    ['Sunflower', 'Hoa hướng dương', 'ground'], ['Tulip', 'Hoa tulip', 'ground'], ['Rose', 'Hoa hồng', 'ground'], ['Hibiscus', 'Hoa dâm bụt', 'ground'],
    ['Cherry blossom', 'Hoa anh đào', 'any'], ['Blossom', 'Bông hoa vàng', 'ground'], ['Bouquet', 'Bó hoa', 'ground'], ['Butterfly', 'Con bướm', 'sky'],
    ['Honeybee', 'Con ong', 'sky'], ['Lady beetle', 'Bọ rùa', 'ground'], ['Snail', 'Con ốc sên', 'ground'], ['Potted plant', 'Chậu cây', 'ground'],
    ['Seedling', 'Mầm cây', 'ground'], ['Four leaf clover', 'Cỏ bốn lá', 'ground'], ['Lotus', 'Hoa sen', 'ground'], ['White flower', 'Hoa trắng', 'ground'],
    ['Wilted flower', 'Hoa héo', 'ground'], ['Cactus', 'Cây xương rồng', 'ground'], ['Bug', 'Con sâu', 'ground'], ['Worm', 'Con giun', 'ground'],
    ['Bird', 'Chú chim', 'sky'], ['Sun', 'Mặt trời', 'sky'], ['Rainbow', 'Cầu vồng', 'sky'], ['Cloud', 'Đám mây', 'sky'],
    ['Hyacinth', 'Hoa lục bình', 'ground'], ['Herb', 'Cây lá', 'ground'], ['Mushroom', 'Cây nấm', 'ground'], ['Frog', 'Con ếch', 'ground'] ] },
  city: { vn: 'Phố xá', bg: 'day-city', items: [
    ['Automobile', 'Ô tô đỏ', 'ground'], ['Bus', 'Xe buýt', 'ground'], ['Taxi', 'Xe taxi', 'ground'], ['Bicycle', 'Xe đạp', 'ground'],
    ['Motor scooter', 'Xe máy', 'ground'], ['Ambulance', 'Xe cứu thương', 'ground'], ['Fire engine', 'Xe cứu hoả', 'ground'], ['Police car', 'Xe cảnh sát', 'ground'],
    ['Delivery truck', 'Xe tải', 'ground'], ['Vertical traffic light', 'Đèn giao thông', 'ground'], ['House', 'Ngôi nhà', 'ground'], ['School', 'Trường học', 'ground'],
    ['Hospital', 'Bệnh viện', 'ground'], ['Convenience store', 'Cửa hàng', 'ground'], ['Tram', 'Tàu điện', 'ground'], ['Airplane', 'Máy bay', 'sky'],
    ['Helicopter', 'Trực thăng', 'sky'], ['Station', 'Nhà ga', 'ground'], ['Fuel pump', 'Cây xăng', 'ground'], ['Construction', 'Rào công trình', 'ground'],
    ['Sport utility vehicle', 'Xe SUV', 'ground'], ['Racing car', 'Xe đua', 'ground'], ['Kick scooter', 'Xe trượt', 'ground'], ['Pickup truck', 'Xe bán tải', 'ground'],
    ['Stop sign', 'Biển dừng', 'ground'], ['Bank', 'Ngân hàng', 'ground'], ['Post office', 'Bưu điện', 'ground'], ['Cloud', 'Đám mây', 'sky'] ] },
  kitchen: { vn: 'Bữa picnic', bg: 'picnic', items: [
    ['Pizza', 'Bánh pizza', 'any'], ['Hamburger', 'Bánh hamburger', 'any'], ['Cooked rice', 'Bát cơm', 'any'], ['Sushi', 'Sushi', 'any'],
    ['Steaming bowl', 'Bát phở', 'any'], ['Bread', 'Bánh mì', 'any'], ['Cheese wedge', 'Miếng phô mai', 'any'], ['Egg', 'Quả trứng', 'any'],
    ['Shallow pan of food', 'Chảo đồ ăn', 'any'], ['Teapot', 'Ấm trà', 'any'], ['Chopsticks', 'Đôi đũa', 'any'], ['Spoon', 'Cái thìa', 'any'],
    ['Bento box', 'Hộp cơm', 'any'], ['Fork and knife', 'Dao dĩa', 'any'], ['Hot beverage', 'Cốc nước nóng', 'any'], ['Glass of milk', 'Cốc sữa', 'any'],
    ['Croissant', 'Bánh sừng bò', 'any'], ['Pancakes', 'Bánh kếp', 'any'], ['Bacon', 'Thịt xông khói', 'any'], ['Poultry leg', 'Đùi gà', 'any'],
    ['Dumpling', 'Bánh bao', 'any'], ['Rice ball', 'Cơm nắm', 'any'], ['Taco', 'Bánh taco', 'any'], ['Hot dog', 'Xúc xích kẹp', 'any'],
    ['Pot of food', 'Nồi lẩu', 'any'], ['Salt', 'Lọ muối', 'any'], ['Honey pot', 'Hũ mật ong', 'any'], ['Kitchen knife', 'Con dao', 'any'] ] },
  winter: { vn: 'Mùa đông tuyết', bg: 'snow', items: [
    ['Snowman', 'Người tuyết', 'ground'], ['Snowflake', 'Bông tuyết', 'sky'], ['Gloves', 'Đôi găng tay', 'ground'], ['Scarf', 'Khăn quàng', 'ground'],
    ['Christmas tree', 'Cây thông Noel', 'ground'], ['Skis', 'Ván trượt tuyết', 'ground'], ['Ice skate', 'Giày trượt băng', 'ground'], ['Hot beverage', 'Cốc nước nóng', 'ground'],
    ['Penguin', 'Chim cánh cụt', 'ground'], ['Polar bear', 'Gấu Bắc Cực', 'ground'], ['Sled', 'Xe trượt tuyết', 'ground'], ['Cloud with snow', 'Mây tuyết', 'sky'],
    ['Coat', 'Áo khoác', 'ground'], ['Billed cap', 'Mũ lưỡi trai', 'ground'], ['Ice', 'Cục đá', 'ground'], ['Wrapped gift', 'Hộp quà', 'ground'],
    ['Bell', 'Cái chuông', 'sky'], ['Candle', 'Cây nến', 'ground'], ['Deer', 'Con nai', 'ground'], ['Owl', 'Con cú', 'sky'],
    ['Fox', 'Con cáo', 'ground'], ['Rabbit', 'Chú thỏ', 'ground'], ['Evergreen tree', 'Cây thông', 'ground'], ['Snow-capped mountain', 'Núi tuyết', 'ground'],
    ['Cookie', 'Bánh quy', 'ground'], ['Socks', 'Đôi tất', 'ground'], ['Star', 'Ngôi sao', 'sky'], ['Crescent moon', 'Trăng khuyết', 'sky'] ] },
  space: { vn: 'Vũ trụ', bg: 'space', items: [
    ['Rocket', 'Tên lửa', 'any'], ['Flying saucer', 'Đĩa bay', 'any'], ['Satellite', 'Vệ tinh', 'any'], ['Ringed planet', 'Sao Thổ', 'any'],
    ['Star', 'Ngôi sao', 'any'], ['Comet', 'Sao chổi', 'any'], ['Full moon', 'Trăng tròn', 'any'], ['Telescope', 'Kính thiên văn', 'any'],
    ['Alien', 'Người ngoài hành tinh', 'any'], ['Alien monster', 'Quái vật vũ trụ', 'any'], ['Robot', 'Người máy', 'any'], ['Globe showing asia-australia', 'Trái Đất', 'any'],
    ['Sun', 'Mặt trời', 'any'], ['Glowing star', 'Sao lấp lánh', 'any'], ['New moon face', 'Mặt trăng tối', 'any'], ['Crescent moon', 'Trăng khuyết', 'any'],
    ['First quarter moon face', 'Mặt trăng cười', 'any'], ['Satellite antenna', 'Chảo ăng-ten', 'any'], ['Sparkles', 'Tia lấp lánh', 'any'], ['Magnet', 'Nam châm', 'any'],
    ['Crystal ball', 'Quả cầu pha lê', 'any'], ['Gem stone', 'Viên ngọc', 'any'], ['Light bulb', 'Bóng đèn', 'any'], ['Battery', 'Cục pin', 'any'],
    ['Joystick', 'Cần điều khiển', 'any'], ['Dna', 'Chuỗi ADN', 'any'], ['Test tube', 'Ống nghiệm', 'any'], ['Microscope', 'Kính hiển vi', 'any'] ] },
  zoo: { vn: 'Sở thú', bg: 'day-savanna', items: [
    ['Lion', 'Sư tử', 'ground'], ['Tiger', 'Con hổ', 'ground'], ['Elephant', 'Con voi', 'ground'], ['Giraffe', 'Hươu cao cổ', 'ground'],
    ['Zebra', 'Ngựa vằn', 'ground'], ['Monkey', 'Con khỉ', 'ground'], ['Panda', 'Gấu trúc', 'ground'], ['Koala', 'Gấu koala', 'ground'],
    ['Kangaroo', 'Chuột túi', 'ground'], ['Hippopotamus', 'Hà mã', 'ground'], ['Rhinoceros', 'Tê giác', 'ground'], ['Parrot', 'Con vẹt', 'sky'],
    ['Flamingo', 'Hồng hạc', 'ground'], ['Peacock', 'Con công', 'ground'], ['Crocodile', 'Cá sấu', 'ground'], ['Camel', 'Lạc đà', 'ground'],
    ['Gorilla', 'Khỉ đột', 'ground'], ['Orangutan', 'Đười ươi', 'ground'], ['Sloth', 'Con lười', 'ground'], ['Llama', 'Lạc đà không bướu', 'ground'],
    ['Leopard', 'Con báo', 'ground'], ['Snake', 'Con rắn', 'ground'], ['Swan', 'Thiên nga', 'ground'], ['Dodo', 'Chim dodo', 'ground'],
    ['Otter', 'Rái cá', 'ground'], ['Skunk', 'Chồn hôi', 'ground'], ['Bison', 'Bò rừng', 'ground'], ['Palm tree', 'Cây dừa', 'ground'] ] },
}
